# Generated by Django 3.2 on 2021-04-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_velocity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='velocity',
        ),
    ]
