# Generated by Django 3.1.4 on 2021-02-17 15:29

import apps.project.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('importance', models.BooleanField(default=False)),
                ('urgency', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=models.SET(apps.project.models.get_sentinel_user), related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('aim', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('estimated_length', models.IntegerField(default=1)),
                ('responsible_role', models.CharField(max_length=255)),
                ('resources', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('ongoing', 'Ongoing'), ('testing', 'Testing'), ('done', 'Done'), ('archived', 'Archived')], default='todo', max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=models.SET(apps.project.models.get_sentinel_user), related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
                ('is_tracked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='project.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='project.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
