# Generated by Django 3.1.4 on 2021-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Закрытый')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='aim',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='resources',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible_role',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Сделать'), ('ongoing', 'В процессе'), ('testing', 'Тестируется'), ('done', 'Сделано'), ('archived', 'В архиве')], default='todo', max_length=20),
        ),
    ]
