# Generated by Django 3.1.4 on 2021-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210218_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_length',
            field=models.IntegerField(choices=[(1, 'O'), (2, 'T'), (3, 'Th'), (5, 'F'), (8, 'E')], default=1),
        ),
    ]
