# Generated by Django 3.1.4 on 2021-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210219_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_length',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (8, '8')], default=1),
        ),
    ]
