# Generated by Django 3.2 on 2021-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210327_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
