# Generated by Django 3.2 on 2021-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
