# Generated by Django 3.2 on 2021-04-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_task_done_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
